server:
  port: 8085

spring:
  application:
    name: product-server
  datasource:
    url: jdbc:postgresql://localhost:5432/online-store-cloud
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

eureka:
  client:
    serviceUrl.defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
    fetch-registry: true
